#ifndef INC_2D_STENCIL_MULTI_THREADED_ONE_BLOCK_COMM_LAYER_NO_COMPUTE_CUH
#define INC_2D_STENCIL_MULTI_THREADED_ONE_BLOCK_COMM_LAYER_NO_COMPUTE_CUH

#include "../common.h"

namespace SSMultiThreadedOneBlockCommLayerNoCompute {
int init(int argc, char** argv);
}

#endif  // INC_2D_STENCIL_MULTI_THREADED_ONE_BLOCK_COMM_LAYER_NO_COMPUTE_CUH
