#ifndef INC_3D_STENCIL_BASELINE_MULTI_THREADED_NVSHMEM_OPT_NO_COMPUTE_CUH
#define INC_3D_STENCIL_BASELINE_MULTI_THREADED_NVSHMEM_OPT_NO_COMPUTE_CUH

#include "../common.h"

namespace BaselineMultiThreadedNvshmemOptNoCompute {
int init(int argc, char **argv);
}

#endif  // INC_3D_STENCIL_BASELINE_MULTI_THREADED_NVSHMEM_OPT_NO_COMPUTE_CUH
