#ifndef INC_NVSHMEM_3D_STENCIL_MULTI_THREADED_TWO_BLOCK_COMM_NO_COMPUTE_CUH
#define INC_NVSHMEM_3D_STENCIL_MULTI_THREADED_TWO_BLOCK_COMM_NO_COMPUTE_CUH

#include "../common.h"

namespace SSMultiThreadedTwoBlockCommNvshmemNoCompute {
int init(int argc, char** argv);
}

#endif  // INC_NVSHMEM_3D_STENCIL_MULTI_THREADED_TWO_BLOCK_COMM_NO_COMPUTE_CUH
