#ifndef INC_3D_STENCIL_BASELINE_MULTI_THREADED_COPY_OVERLAP_NO_COMM_CUH
#define INC_3D_STENCIL_BASELINE_MULTI_THREADED_COPY_OVERLAP_NO_COMM_CUH

#include "../common.h"

namespace BaselineMultiThreadedCopyOverlapNoComm {
int init(int argc, char **argv);
}

#endif  // INC_3D_STENCIL_BASELINE_MULTI_THREADED_COPY_OVERLAP_NO_COMM_CUH
