#ifndef INC_CG_BASELINE_PERSISTENT_UNIFIED_MEMORY_STALE_DEVICE_VECTOR_CUH
#define INC_CG_BASELINE_PERSISTENT_UNIFIED_MEMORY_STALE_DEVICE_VECTOR_CUH

#include "../common.h"

namespace BaselinePersistentUnifiedMemoryStaleDeviceVector {
int init(int argc, char **argv);
}

#endif  // INC_CG_BASELINE_PERSISTENT_UNIFIED_MEMORY_STALE_DEVICE_VECTOR_CUH
