#ifndef INC_3D_STENCIL_BASELINE_MULTI_THREADED_COPY_OVERLAP_NO_COMPUTE_CUH
#define INC_3D_STENCIL_BASELINE_MULTI_THREADED_COPY_OVERLAP_NO_COMPUTE_CUH

#include "../common.h"

namespace BaselineMultiThreadedCopyOverlapNoCompute {
int init(int argc, char **argv);
}

#endif  // INC_3D_STENCIL_BASELINE_MULTI_THREADED_COPY_OVERLAP_NO_COMPUTE_CUH
