#ifndef INC_3D_STENCIL_MULTI_THREADED_ONE_BLOCK_WARP_COMM_NO_COMPUTE_CUH
#define INC_3D_STENCIL_MULTI_THREADED_ONE_BLOCK_WARP_COMM_NO_COMPUTE_CUH

#include "../common.h"

namespace SSMultiThreadedOneBlockWarpCommNoCompute {
int init(int argc, char** argv);
}

#endif  // INC_3D_STENCIL_MULTI_THREADED_ONE_BLOCK_WARP_COMM_NO_COMPUTE_CUH
