#ifndef INC_NVSHMEM_3D_STENCIL_MULTI_THREADED_ONE_BLOCK_COMM_LAYER_PUT_NO_COMPUTE_CUH
#define INC_NVSHMEM_3D_STENCIL_MULTI_THREADED_ONE_BLOCK_COMM_LAYER_PUT_NO_COMPUTE_CUH

#include "../common.h"

namespace SSMultiThreadedOneBlockCommLayerPutNvshmemNoCompute {
int init(int argc, char** argv);
}

#endif  // INC_NVSHMEM_3D_STENCIL_MULTI_THREADED_ONE_BLOCK_COMM_LAYER_PUT_NO_COMPUTE_CUH
