#ifndef INC_NVSHMEM_3D_STENCIL_MULTI_THREADED_ONE_BLOCK_COMM_BULK_GET_NO_COMPUTE_CUH
#define INC_NVSHMEM_3D_STENCIL_MULTI_THREADED_ONE_BLOCK_COMM_BULK_GET_NO_COMPUTE_CUH

#include "../common.h"

namespace SSMultiThreadedOneBlockCommBulkGetNvshmemNoCompute {
int init(int argc, char** argv);
}

#endif  // INC_NVSHMEM_3D_STENCIL_MULTI_THREADED_ONE_BLOCK_COMM_BULK_GET_NO_COMPUTE_CUH
