#ifndef INC_NVSHMEM_3D_STENCIL_MULTI_THREADED_ONE_BLOCK_COMM_ORIGINAL_H
#define INC_NVSHMEM_3D_STENCIL_MULTI_THREADED_ONE_BLOCK_COMM_ORIGINAL_H

#include "../common.h"

namespace SSMultiThreadedOneBlockCommOriginalNvshmem {
int init(int argc, char** argv);
}

#endif  // INC_NVSHMEM_3D_STENCIL_MULTI_THREADED_ONE_BLOCK_COMM_ORIGINAL_H
