#ifndef INC_NVSHMEM_3D_STENCIL_MULTI_THREADED_ONE_BLOCK_THREAD_GET_COMM_H
#define INC_NVSHMEM_3D_STENCIL_MULTI_THREADED_ONE_BLOCK_THREAD_GET_COMM_H

#include "../common.h"

namespace SSMultiThreadedOneBlockCommThreadGetNvshmem {
int init(int argc, char** argv);
}

#endif  // INC_NVSHMEM_3D_STENCIL_MULTI_THREADED_ONE_BLOCK_THREAD_GET_COMM_H
