#ifndef INC_NVSHMEM_3D_STENCIL_MULTI_THREADED_TWO_BLOCK_COMM_CONTIGUOUS_H
#define INC_NVSHMEM_3D_STENCIL_MULTI_THREADED_TWO_BLOCK_COMM_CONTIGUOUS_H

#include "../common.h"

namespace SSMultiThreadedTwoBlockCommContiguousNvshmem {
int init(int argc, char** argv);
}

#endif  // INC_NVSHMEM_3D_STENCIL_MULTI_THREADED_TWO_BLOCK_COMM_CONTIGUOUS_H