#ifndef INC_NVSHMEM_3D_STENCIL_MULTI_THREADED_ONE_BLOCK_COMM_ORIGINAL_GET_CUH
#define INC_NVSHMEM_3D_STENCIL_MULTI_THREADED_ONE_BLOCK_COMM_ORIGINAL_GET_CUH

#include "../common.h"

namespace SSMultiThreadedOneBlockCommOriginalGetNvshmem {
int init(int argc, char** argv);
}

#endif  // INC_NVSHMEM_3D_STENCIL_MULTI_THREADED_ONE_BLOCK_COMM_ORIGINAL_GET_CUH
