#ifndef INC_NVSHMEM_3D_STENCIL_MULTI_THREADED_ONE_BLOCK_THREAD_PUT_COMM_H
#define INC_NVSHMEM_3D_STENCIL_MULTI_THREADED_ONE_BLOCK_THREAD_PUT_COMM_H

#include "../common.h"

namespace SSMultiThreadedOneBlockCommThreadPutNvshmem {
int init(int argc, char** argv);
}

#endif  // INC_NVSHMEM_3D_STENCIL_MULTI_THREADED_ONE_BLOCK_THREAD_PUT_COMM_H
