#ifndef INC_NVSHMEM_3D_3D_STENCIL_MULTI_THREADED_TWO_BLOCK_WARP_COMM_CUH
#define INC_NVSHMEM_3D_3D_STENCIL_MULTI_THREADED_TWO_BLOCK_WARP_COMM_CUH

#include "../common.h"

namespace SSMultiThreadedTwoBlockWarpCommNvshmem {
int init(int argc, char** argv);
}

#endif  // INC_NVSHMEM_3D_3D_STENCIL_MULTI_THREADED_TWO_BLOCK_WARP_COMM_CUH
