#ifndef INC_NVSHMEM_3D_STENCIL_MULTI_THREADED_TWO_BLOCK_COMM_NO_COMM_CUH
#define INC_NVSHMEM_3D_STENCIL_MULTI_THREADED_TWO_BLOCK_COMM_NO_COMM_CUH

#include "../common.h"

namespace SSMultiThreadedTwoBlockCommNvshmemNoComm {
int init(int argc, char** argv);
}

#endif  // INC_NVSHMEM_3D_STENCIL_MULTI_THREADED_TWO_BLOCK_COMM_NO_COMM_CUH
