#ifndef INC_NVSHMEM_3D_STENCIL_MULTI_GPU_PEER_TILING_NVSHMEM_NO_COMM_CUH
#define INC_NVSHMEM_3D_STENCIL_MULTI_GPU_PEER_TILING_NVSHMEM_NO_COMM_CUH

#include "../common.h"

namespace MultiGPUPeerTilingNvshmemNoComm {
int init(int argc, char** argv);
}

#endif  // INC_NVSHMEM_3D_STENCIL_MULTI_GPU_PEER_TILING_NVSHMEM_NO_COMM_CUH
