#ifndef INC_NVSHMEM_3D_STENCIL_BASELINE_MULTI_THREADED_NVSHMEM_NO_COMM_CUH
#define INC_NVSHMEM_3D_STENCIL_BASELINE_MULTI_THREADED_NVSHMEM_NO_COMM_CUH

#include "../common.h"

namespace BaselineMultiThreadedNvshmemNoComm {
int init(int argc, char **argv);
}

#endif  // INC_NVSHMEM_3D_STENCIL_BASELINE_MULTI_THREADED_NVSHMEM_NO_COMM_CUH
